# -*- coding: utf-8 -*-
"""Handwritten_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QwrLDRIXThr3EY5J5_nh0A7JcQuCRaT_
"""

import streamlit as st
import easyocr
from docx import Document

def handwritten_to_word(image_path):
    # Perform OCR on the handwritten image
    reader = easyocr.Reader(['en'])
    results = reader.readtext(image_path)

    # Extract and concatenate recognized text
    recognized_text = ' '.join([result[1] for result in results])

    return recognized_text

def main():
    st.title("Handwritten Text Recognition")

    uploaded_file = st.file_uploader("Upload handwritten image", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        # Display the uploaded image
        st.image(uploaded_file, caption="Uploaded Image", use_column_width=True)

        # Convert handwritten text to Word document on button click
        if st.button("Recognize Text"):
            recognized_text = handwritten_to_word(uploaded_file)
            st.write("Recognized Text:")
            st.write(recognized_text)

if __name__ == "__main__":
    main()